/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;
import java.util.Stack;
/**
 *
 * @author arpit
 */
public class startGUI extends javax.swing.JFrame {

    /**
     * Creates new form startGUI
     */
    
    double firstnum, secondnum, result;
    String operations;
    
    public startGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxt_display = new javax.swing.JTextField();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn_decimal = new javax.swing.JButton();
        jbtnadd1 = new javax.swing.JButton();
        jbtnsub1 = new javax.swing.JButton();
        jbtnmult1 = new javax.swing.JButton();
        jbtndiv1 = new javax.swing.JButton();
        jbtnpower1 = new javax.swing.JButton();
        jbtn_left_par = new javax.swing.JButton();
        jbtn10 = new javax.swing.JButton();
        jbtn11 = new javax.swing.JButton();
        jbtn_right_par1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxt_display.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxt_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxt_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 40));

        jbtn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 60));

        jbtn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 70, 60));

        jbtn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 60));

        jbtn4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 60));

        jbtn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 70, 60));

        jbtn6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 70, 60));

        jbtn7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 60));

        jbtn8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 70, 60));

        jbtn9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, 60));

        jbtn0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtn0.setText("C");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, 130));

        jbtn_decimal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtn_decimal.setText(".");
        jbtn_decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_decimalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 170, 40));

        jbtnadd1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnadd1.setText("+");
        jbtnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnadd1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 40));

        jbtnsub1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnsub1.setText("-");
        jbtnsub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsub1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, 40));

        jbtnmult1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnmult1.setText("*");
        jbtnmult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmult1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmult1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 40));

        jbtndiv1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtndiv1.setText("/");
        jbtndiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndiv1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndiv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 40));

        jbtnpower1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnpower1.setText("^");
        jbtnpower1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpower1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnpower1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 40));

        jbtn_left_par.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtn_left_par.setText("(");
        jbtn_left_par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_left_parActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_left_par, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 40));

        jbtn10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtn10.setText("0");
        jbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn10ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, 50));

        jbtn11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtn11.setText("=");
        jbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn11ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 130));

        jbtn_right_par1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtn_right_par1.setText(")");
        jbtn_right_par1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_right_par1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_right_par1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "1");
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "6");
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "5");
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "2");
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "3");
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "4");
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "7");
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "8");
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "9");
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn10ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "0");
    }//GEN-LAST:event_jbtn10ActionPerformed

    private void jbtnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnadd1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "+");
    }//GEN-LAST:event_jbtnadd1ActionPerformed

    private void jbtnsub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsub1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "-");
    }//GEN-LAST:event_jbtnsub1ActionPerformed

    private void jbtnmult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmult1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "*");
    }//GEN-LAST:event_jbtnmult1ActionPerformed

    private void jbtndiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndiv1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "/");
    }//GEN-LAST:event_jbtndiv1ActionPerformed

    private void jbtnpower1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpower1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "^");
    }//GEN-LAST:event_jbtnpower1ActionPerformed

    private void jbtn_left_parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_left_parActionPerformed
        jtxt_display.setText( jtxt_display.getText() + "(");
    }//GEN-LAST:event_jbtn_left_parActionPerformed

    private void jbtn_right_par1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_right_par1ActionPerformed
        jtxt_display.setText( jtxt_display.getText() + ")");
    }//GEN-LAST:event_jbtn_right_par1ActionPerformed

    private void jbtn_decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_decimalActionPerformed
        jtxt_display.setText( jtxt_display.getText() + ".");
    }//GEN-LAST:event_jbtn_decimalActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        jtxt_display.setText( jtxt_display.getText().substring(0, jtxt_display.getText().length()-1));
    }//GEN-LAST:event_jbtn0ActionPerformed
    
    public int evaluate(String expression)
    {
        char[] tokens = expression.toCharArray();
        Stack<Integer> values = new Stack();
        Stack<Character> ops = new Stack();
 
        for (int i = 0; i < tokens.length; i++)
        {
             // Current token is a whitespace, skip it
            if (tokens[i] == ' ')
                continue;
 
            // Current token is a number, push it to stack for numbers
            if (tokens[i] >= '0' && tokens[i] <= '9')
            {
                StringBuilder sbuf = new StringBuilder();
                // There may be more than one digits in number
                while (i < tokens.length && tokens[i] >= '0' && tokens[i] <= '9')
                    sbuf.append(tokens[i++]);
                i--;
                values.push(Integer.parseInt(sbuf.toString()));
            }
 
            // Current token is an opening brace, push it to 'ops'
            else if (tokens[i] == '(')
                ops.push(tokens[i]);
 
            // Closing brace encountered, solve entire brace
            else if (tokens[i] == ')')
            {
                while (ops.peek() != '(')
                  values.push(applyOp(ops.pop(), values.pop(), values.pop()));
                ops.pop();
            }
 
            // Current token is an operator.
            else if (tokens[i] == '+' || tokens[i] == '-' ||
                     tokens[i] == '*' || tokens[i] == '/'|| tokens[i] == '^')
            {
                // While top of 'ops' has same or greater precedence to current
                // token, which is an operator. Apply operator on top of 'ops'
                // to top two elements in values stack
                while (!ops.empty() && hasPrecedence(tokens[i], ops.peek()))
                  values.push(applyOp(ops.pop(), values.pop(), values.pop()));
 
                // Push current token to 'ops'.
                ops.push(tokens[i]);
            }
        }
 
        // Entire expression has been parsed at this point, apply remaining
        // ops to remaining values
        while (!ops.empty())
            values.push(applyOp(ops.pop(), values.pop(), values.pop()));
 
        // Top of 'values' contains result, return it
        return values.pop();
    }
 
    // Returns true if 'op2' has higher or same precedence as 'op1',
    // otherwise returns false.
    public boolean hasPrecedence(char op1, char op2)
    {
        if (op2 == '(' || op2 == ')')
            return false;
        else if ((op1 == '*' || op1 == '/') && (op2 == '+' || op2 == '-'))
            return false;
        if ((op1 == '^') && (op2 == '*' || op2 == '/'||op2 == '+' || op2 == '-'))
                    return false;
        else
            return true;
    }
 
    // A utility method to apply an operator 'op' on operands 'a' 
    // and 'b'. Return the result.
    public int applyOp(char op, int b, int a)
    {
        switch (op)
        {
        case '+':
            return a + b;
        case '-':
            return a - b;
        case '*':
            return a * b;
        case '/':
            if (b == 0)
                throw new
                UnsupportedOperationException("Cannot divide by zero");
            return a / b;
        case '^':
            return (int)Math.pow(a, b);
        }
        return 0;
    }
    
    private void jbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn11ActionPerformed
        String answer = evaluate( jtxt_display.getText()) + "";
        System.out.println(answer);
        jtxt_display.setText( answer);
    }//GEN-LAST:event_jbtn11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn10;
    private javax.swing.JButton jbtn11;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtn_decimal;
    private javax.swing.JButton jbtn_left_par;
    private javax.swing.JButton jbtn_right_par1;
    private javax.swing.JButton jbtnadd1;
    private javax.swing.JButton jbtndiv1;
    private javax.swing.JButton jbtnmult1;
    private javax.swing.JButton jbtnpower1;
    private javax.swing.JButton jbtnsub1;
    private javax.swing.JTextField jtxt_display;
    // End of variables declaration//GEN-END:variables
}
